# configs/demo/annotation.yaml
# Process config for human preference annotation with Label Studio

# Global parameters
project_name: 'demo-annotation-human-preference'
dataset_path: './demos/data/demo-dataset-annotation-human-preference.jsonl'
np: 1  # Use single process for annotation tasks
open_tracer: true

# Specify which field to use as the primary text field
text_keys: "prompt"  # This tells Data Juicer to use "prompt" as the text field

export_path: './outputs/demo-annotation-human-preference/annotated-data.jsonl'

# Process schedule
process:
  # Annotation step using Label Studio with human preference
  - human_preference_annotation_mapper:
      # Connection settings
      api_url: "http://localhost:7070"  # Default Label Studio URL
      api_key: "8fd61618b3027d3eecff3c4be6ba368db6bf14c7"  # Your API key from label_studio_connection.json

      # Annotation settings
      project_name: "Human Preference Annotation"
      wait_for_annotations: true  # Whether to wait for annotations to complete
      timeout: 3600  # Maximum time to wait for annotations in seconds (1 hour)
      poll_interval: 10  # Time between annotation status checks in seconds
      samples_per_task: 1  # One sample per task for pairwise comparison
      max_tasks_per_batch: 10  # Maximum number of tasks in a single batch

      # Data field mappings - these match the fields in the JSONL file
      answer1_key: "answer1"  # First answer option
      answer2_key: "answer2"  # Second answer option

      # Label Studio template file
      label_config_file: "./label_studio_templates/human_preference.xml"

      # Notification settings (optional)
      notification_config:
        enabled: false
